version: "2.4"

services:
  ros2_bridge:
    image: kachaka-api:latest
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - API_GRPC_BRIDGE_SERVER_URI
      - ROS_DOMAIN_ID
      - ROS_LOCALHOST_ONLY
      - ROS_LOG_DIR=/tmp
      - RMW_IMPLEMENTATION
      - USER_ID
      - GROUP_ID
    user: "${USER_ID}:${GROUP_ID}"
    command: >
      ros2 launch kachaka_grpc_ros2_bridge grpc_ros2_bridge.launch.xml server_uri:=${API_GRPC_BRIDGE_SERVER_URI}
  kachaka_follow:
    image: kachaka-api:latest
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - ROS_DOMAIN_ID
      - ROS_LOCALHOST_ONLY
      - ROS_LOG_DIR=/tmp
      - RMW_IMPLEMENTATION
      - USER_ID
      - GROUP_ID
    user: "${USER_ID}:${GROUP_ID}"
    command: >
      ros2 run kachaka_follow follow
  kachaka_speak:
    image: kachaka-api:latest
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - ROS_DOMAIN_ID
      - ROS_LOCALHOST_ONLY
      - ROS_LOG_DIR=/tmp
      - RMW_IMPLEMENTATION
      - USER_ID
      - GROUP_ID
    user: "${USER_ID}:${GROUP_ID}"
    command: >
      ros2 run kachaka_speak speak
  kachaka_smart_speaker:
    image: kachaka-api:latest
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - ROS_DOMAIN_ID
      - ROS_LOCALHOST_ONLY
      - ROS_LOG_DIR=/tmp
      - RMW_IMPLEMENTATION
      - USER_ID
      - GROUP_ID
    user: "${USER_ID}:${GROUP_ID}"
    command: >
      ros2 run kachaka_smart_speaker smart_speaker
  kachaka_vision:
    image: kachaka-api:latest
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - ROS_DOMAIN_ID
      - ROS_LOCALHOST_ONLY
      - ROS_LOG_DIR=/tmp
      - RMW_IMPLEMENTATION
      - USER_ID
      - GROUP_ID
    user: "${USER_ID}:${GROUP_ID}"
    command: >
      ros2 launch kachaka_vision hand_recognition_launch.py
